---
# handlers file for varnish

- name: restart varnish
  become: yes
  service:
    name: "{{ varnish_service_name }}"
    state: restarted
  tags:
    - varnish

- name: reload varnish
  become: yes
  service:
    name: "{{ varnish_service_name }}"
    state: reloaded
  tags:
    - varnish
